webtalk_init -webtalk_dir C:/Users/Emman/Documents/GitHub/pipelined-RV32IMC/Vivado Project/pipelined-RV32IMC.sim/sim_1/behav/xsim/xsim.dir/tb_core_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 30 19:43:15 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "16c26433-4cc6-48a7-a863-4216a85071b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c8cf415cb9774e28b02a4072365dbdd1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "88" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "895 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6516_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4178448870 -regid "" -xml C:/Users/Emman/Documents/GitHub/pipelined-RV32IMC/Vivado Project/pipelined-RV32IMC.sim/sim_1/behav/xsim/xsim.dir/tb_core_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Emman/Documents/GitHub/pipelined-RV32IMC/Vivado Project/pipelined-RV32IMC.sim/sim_1/behav/xsim/xsim.dir/tb_core_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Emman/Documents/GitHub/pipelined-RV32IMC/Vivado Project/pipelined-RV32IMC.sim/sim_1/behav/xsim/xsim.dir/tb_core_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
