# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/MJ/Documents/Vivado/pipelined-RV32IMC/pipelined-RV32IMC.srcs/sources_1/ip/blk_mem_gen_datamem/blk_mem_gen_datamem.xci
# IP: The module: 'blk_mem_gen_datamem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MJ/Documents/Vivado/pipelined-RV32IMC/pipelined-RV32IMC.srcs/sources_1/ip/blk_mem_gen_datamem/blk_mem_gen_datamem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_datamem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/MJ/Documents/Vivado/pipelined-RV32IMC/pipelined-RV32IMC.srcs/sources_1/ip/blk_mem_gen_datamem/blk_mem_gen_datamem.xci
# IP: The module: 'blk_mem_gen_datamem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MJ/Documents/Vivado/pipelined-RV32IMC/pipelined-RV32IMC.srcs/sources_1/ip/blk_mem_gen_datamem/blk_mem_gen_datamem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_datamem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
